### PR TITLE
Make it work with Silensio city models

### PR DESCRIPTION
**Pull request by auduny**
Hi. This is a fork to be able to retrive info from the gardena silensio city models. It's mostly off by one on the returned arrays. So I am unsure if the api has changed on update or the output is different from your model and mine. If it's different then the code needs some rework to identify the model.

### CODE REVIEW

**Comment by rcastberg** [comment]
Thanks, i think you are right.
i will check in the weekend and accept your pull request.

**Comment by auduny** [comment]
Did you have time to check this during the weekend? Did the api change or is there a array-difference between models?

**Comment by rcastberg** [comment]
Thanks, the same changes were necessary for my mower.

**Comment by auduny** [comment]
Now that the pullrequest is in, it would be awesome if the python package could be updated in the pypi -repo so building home-assistant would be easier. Pretty please :-)

**Comment by rcastberg** [comment]
Sure, i tried today, but had some issues with pip and dependencies, i will ensure it is updated some point early this week.

**Comment by rcastberg** [comment]
Should be up to date now.

**Pull request merged**
